api:
  port: 5000

email:
  developerMode: true
  enabled: true
  developerEmails:
    - yugidazai@gmail.com
    - tara.kaplan@siteminder.com
    - stefano.fratini@siteminder.com
    - nick@tekfinder.io
    - kathydoan87@gmail.com

  providers:
    sendgrid:
      url: https://api.sendgrid.com/v3/mail/send
      apiKey: <CHANGE_ME>
    mailgun:
      url: https://api.mailgun.net/v3/{domain}/messages
      domain: sandboxccebe47c91b840f0b486c2de88579fd3.mailgun.org
      apiKey: <CHANGE_ME>

  messages:
    fail: Sorry, the service is unavailable at the moment! Please try again later.
    success: Great! The email has been sent successfully to {receiver}!
